title: 잡다한 블로그
logo_img: /assets/img/icons/golasblog_logo.svg
favicon: /assets/favicon.ico
description: 공부용
global_tags: jekyll theme simplex golasblog responsive html5
copyright: © fault2000 2022

sass:
    style: compressed

collections:
    category:
        output: true
    authors:
        output: false

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"